Repository RedHatInsights/edge-api, pull requests merged in 2021-12, with the labels that each got.

#407 Remove OwnershipVoucherData from Device && fix DB bugs
  cmd/migrate/migrate.go
  main.go
  pkg/models/ownershipvoucher.go
  pkg/models/updates.go
  pkg/services/main_test.go
  pkg/services/ownershipvoucher.go
  pkg/services/ownershipvoucher_unit_test.go
Labels: waiting for review

#428 pr_check: disabled cji and make dummy report
  pr_check.sh
Labels: do not merge

#490 Add refactor as a possible type of change
  .github/pull_request_template.md
Labels: waiting for review

#495 Use service as an interface
  Dockerfile
  Makefile
  pkg/clients/fdo/client.go
  pkg/clients/fdo/client_test.go
  pkg/clients/fdo/fdo_suite_test.go
  pkg/routes/ownershipvoucher.go
  pkg/routes/ownershipvoucher_active.go
  pkg/routes/ownershipvoucher_test.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/ownershipvoucher.go
  pkg/services/ownershipvoucher_active.go
  pkg/services/ownershipvoucher_test.go
  pkg/services/ownershipvoucher_unit_test.go
  pkg/services/services.go
Labels: enhancement

#489 Add logs to get repo by id and get metadata endpoints
  pkg/dependencies/main.go
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/images.go
  pkg/services/mock_services/images.go
  pkg/services/mock_services/repo.go
  pkg/services/repo.go
  pkg/services/repobuilder.go
Labels: waiting for review

#501 Fixes an Image get orphaned from its imageSet if a previous image build failed.
  pkg/services/images.go
Labels: waiting for review, bug fix

#496 Move create installer to service, refactor to avoid codedup
  pkg/routes/images.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: waiting for review
