Repository RedHatInsights/edge-api, pull requests merged in 2021-11, with the labels that each got.

#349 Create FDO client
  .github/workflows/go.yml
  Makefile
  config/config.go
  deploy/clowdapp.yaml
  pkg/clients/fdo/client.go
  pkg/clients/fdo/client_test.go
  pkg/clients/fdo/fdo_suite_test.go
  pkg/models/ownershipvoucher.go
  pkg/models/ownershipvoucher_test.go
  pkg/ownershipvoucher/deserializer.go
  pkg/ownershipvoucher/deserializer_test.go
  pkg/services/ownershipvoucher/ownershipvoucher.go
  pkg/services/ownershipvoucher/ownershipvoucher_suite_test.go
  pkg/services/ownershipvoucher/ownershipvoucher_test.go
  test-container/Dockerfile
Labels: FDO

#365 FDO using new lib
  pkg/clients/fdo/client_test.go
  pkg/services/ownershipvoucher/ownershipvoucher.go
  pkg/services/ownershipvoucher/ownershipvoucher_test.go
Labels: FDO

#358 Adding mergify.yml for automatic merge on approval
  .github/mergify.yml
Labels: Do not merge

#386 ci(Mergify): configuration update
  .github/mergify.yml
Labels: waiting for review

#388 ci(Mergify): configuration update
  .github/mergify.yml
Labels: waiting for review

#378 FDO service & route
  .github/workflows/go.yml
  Dockerfile
  Makefile
  cmd/spec/main.go
  docs/spec/FDO.md
  go.mod
  go.sum
  main.go
  pkg/clients/fdo/client.go
  pkg/clients/fdo/client_test.go
  pkg/dependencies/main.go
  pkg/models/ownershipvoucher.go
  pkg/models/updates.go
  pkg/routes/ownershipvoucher.go
  pkg/routes/ownershipvoucher_test.go
  pkg/routes/routes_suite_test.go
  pkg/services/ownershipvoucher.go
  pkg/services/ownershipvoucher/ownershipvoucher.go
  pkg/services/ownershipvoucher/ownershipvoucher_suite_test.go
  pkg/services/ownershipvoucher/ownershipvoucher_test.go
  pkg/services/ownershipvoucher_test.go
  test-container/Dockerfile
Labels: FDO, waiting for review

#404 spec-file fixes
  cmd/spec/openapi.json
  cmd/spec/openapi.yaml
  cmd/spec/path.yaml
Labels: waiting for review
