Repository RedHatInsights/edge-api, pull requests merged in 2022-02, with the labels that each got.

#581 Device groups: Create DB structure to "groups".
  cmd/db/wipe.go
  cmd/migrate/main.go
  pkg/models/devicegroups.go
  pkg/models/devicegroups_test.go
  pkg/models/main_test.go
Labels: new feature

#590 Device groups: Get all device groups.
  main.go
  pkg/dependencies/main.go
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/services/devicegroups.go
  pkg/services/mock_services/devicegroups.go
Labels: new feature

#594 THEEDGE-1612 add test for ExtractVersionRepo
  pkg/services/repobuilder_test.go
Labels: test update

#620 Device groups: Add devices.
  cmd/spec/path.yaml
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/routes/main_test.go
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
  pkg/services/errors.go
  pkg/services/main_test.go
  pkg/services/mock_services/devicegroups.go
Labels: new feature

#629 Device groups: device-groups get spec.
  cmd/spec/path.yaml
Labels: new feature

#634 Device groups: FIXES device-group type in service.
  pkg/services/devicegroups.go
Labels: bug fix

#640 THEEDGE-1668 update spec path file
  cmd/spec/path.yaml
Labels: documentation

#648 Download TAR repo: Return full qualified name for tarfile after download
  pkg/services/repobuilder.go
  pkg/services/repobuilder_test.go
Labels: waiting for review

#675 Device Groups: Remove devices.
  cmd/spec/path.yaml
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
  pkg/services/errors.go
  pkg/services/mock_services/devicegroups.go
Labels: new feature

#691 THEEDGE-1636 Convert panic() to LogErrorAndPanic() and ginkgo stub files
  cmd/migrate/main.go
  cmd/migrate/main_test.go
  cmd/migrate/migrate_suite_test.go
Labels: waiting for review

#713 GetDevice: Fix account info.
  pkg/services/devices.go
Labels: bug, waiting for review
