Repository RedHatInsights/edge-api, pull requests merged in 2022-03, with the labels that each got.

#773 events: Process Kafka platform inventory delete event.
  pkg/services/consumers.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/mock_services/devices.go
Labels: waiting for review

#786 update api-spec file for route get device group details by id
  cmd/spec/main.go
  cmd/spec/path.yaml
Labels: documentation

#790 THEEDGE-1929 Log postgres information
  pkg/db/db.go
  pkg/services/images.go
Labels: waiting for review

#780 devices: FIXES devices db route need pagination handler.
  pkg/routes/devices.go
Labels: waiting for review

#854 devices events: FIXES inventory delete event.
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: bug fix

#868 Added Arch/OS/Distribution options (default for now)
  .travis.yml
Labels: waiting for review
