Repository RedHatInsights/edge-api, pull requests merged in 2022-11, with the labels that each got.

#1612 add total packages to be used on FE
  pkg/models/images.go
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: waiting for review, new feature

#1617 add total system running and if can update between current and update…
  pkg/models/images.go
  pkg/services/commits_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: new feature

#1622 Add pagination to update available
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/mock_services/devices.go
Labels: waiting for review, bug fix, new feature

#1628 fix error message return to the endpoint
  pkg/routes/updates.go
  pkg/routes/updates_test.go
  pkg/services/commits.go
  pkg/services/commits_test.go
  pkg/services/errors.go
Labels: bug fix

#1629 Rename image info
  pkg/models/images.go
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: new feature

#1632 images: FIXES image update when previous image failed.
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug fix

#1633 fixes /devices filters
  cmd/spec/path.yaml
  pkg/routes/query_params.go
Labels: documentation, bug fix

#1635 add support to rhel-87
  config/config_suite_test.go
  config/config_test.go
  config/repo_config.go
  config/repo_config_test.go
  pkg/clients/imagebuilder/client_test.go
  pkg/common/kafka/kafka_suite_test.go
  pkg/models/events_test.go
Labels: new feature

#1641 updated spec-file description for /devices order_how query param
  cmd/spec/path.yaml
Labels: documentation

#1642 storage: Create storage images commits repositories endpoints.
  cmd/spec/path.yaml
  pkg/routes/storage.go
  pkg/routes/storage_test.go
Labels: new feature

#1627 fix some spelling mistakes
  pkg/common/kafka/producer.go
  pkg/common/kafka/producer_test.go
Labels: waiting for review

#1652 Display commit hash and fix pre-existing lint error
  main.go
  pkg/models/events_test.go
Labels: bug fix, new feature

#1643 Filter by id on image-sets view route
  cmd/spec/path.yaml
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/routes/query_params.go
Labels: new feature

#1655 Fix 1 code-smell issue and removed unused file.
  pkg/services/updates.go
  sonarqube_exec.sh
Labels: bug fix

#1657 Theedge 2802
  config/repo_config.go
Labels: new feature

#1664 add image completion producers
  pkg/models/events.go
  pkg/routes/common/identity.go
  pkg/routes/common/identity_test.go
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/image/event_image_requested.go
  pkg/services/image/event_image_requested_test.go
  pkg/services/image/event_image_update_requested.go
  pkg/services/image/events.go
  pkg/services/images.go
  pkg/services/images_build/main.go
  pkg/services/mock_services/images.go
  pkg/services/services.go
  pkg/services/updates.go
  podman/Containerfile-dev
  podman/container-compose-api.yml
  podman/container-compose-db.yml
  podman/container-compose-kafka.yml
  podman/container-compose-services.yml
  unleash/features/feature.go
Labels: new feature

#1666 storage: ADD image-builder access to storage images-repos.
  config/config.go
  deploy/clowdapp.yaml
  pkg/routes/storage.go
  pkg/routes/storage_test.go
Labels: enhancement, waiting for review, new feature

#1601 add README for Kafka podman-compose files
  podman/README.md
  podman/env/edgemgmt_config_sasl.json
Labels: documentation

#1640 Added DELETE image endpoint and service. Added function to mark devic…
  cmd/spec/path.yaml
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/errors.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: new feature

#1616 Add Consumer interface to allow mocking.
  pkg/common/kafka/consumer.go
  pkg/common/kafka/consumer_test.go
  pkg/common/kafka/mock_kafka/mock_consumer.go
  pkg/dependencies/main.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/images_iso_suite_test.go
  pkg/services/images_iso/main.go
  pkg/services/images_iso/main_test.go
Labels: new feature

#1670 [THEEDGE-2844] fixed image-set view sort_by params
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/routes/query_params.go
Labels: bug fix, test update

#1676 updated sort_by description in the spec file
  cmd/spec/path.yaml
Labels: documentation

#1660 add total packages and system running to image end point
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: bug fix

#1678 removed query validation from GetImageSetViewByID
  cmd/spec/path.yaml
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
Labels: documentation, waiting for review, bug fix, test update

#1679 image-set-view: FIX image-set image preload data.
  pkg/services/imagesets.go
Labels: bug fix

#1673 image-builder: use storage/images-repos/{imageID} end-point in image-builder requests.
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/services/images.go
  pkg/services/images_test.go
  unleash/features/feature.go
Labels: new feature

#1685 Added condition to DELETE images, if last image, then image set is al…
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug fix

#1683 apiResponse: FIXES routes updates and devices api responses.
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/routes/updates.go
  pkg/routes/updates_test.go
Labels: waiting for review, bug fix

#1689 Add unittests for pkg/services/errors.go
  pkg/routes/updates_test.go
  pkg/services/commits_test.go
  pkg/services/errors.go
  pkg/services/errors_test.go
Labels: waiting for review, test update

#1692 Fixed duplicated commit word in the message error
  pkg/routes/updates_test.go
  pkg/services/errors.go
Labels: bug fix

#1684 fixed delete-image error code
  pkg/routes/images.go
  pkg/routes/images_test.go
Labels: bug fix

#1688 add more unit test to check the getDeviceforImage function
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/routes/main_test.go
  pkg/services/images_test.go
Labels: bug fix

#1674 Adding DELETE for image sets that have no devices using them.
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/services/errors.go
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
  pkg/services/mock_services/imagesets.go
Labels: new feature

#1626 Created event device sync.
  pkg/services/devices.go
  pkg/services/devices/devices_suite_test.go
  pkg/services/devices/event_device_sync.go
  pkg/services/devices/event_device_sync_test.go
  pkg/services/image/event_image_iso_requested.go
  pkg/services/image/event_image_iso_requested_test.go
  pkg/services/image/event_image_requested.go
  pkg/services/image/event_image_requested_test.go
  pkg/services/image/event_image_update_requested.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/main.go
  pkg/services/mock_services/devices.go
  pkg/services/utility/context.go
  pkg/services/utility/errors.go
Labels: new feature

#1686 add signal to image_iso event to support case of interup
  pkg/services/images_iso/main.go
Labels: waiting for review

#1698 updated spec-file with delete-image-set endpoint
  cmd/spec/path.yaml
Labels: documentation

#1701 image-set: fix GetImageSetsBuildIsoURL, remove not needed sql expression
  pkg/services/imagesets.go
Labels: bug fix

#1702 images: HOT FIX GetUpdateInfo limit images to 1.
  pkg/services/images.go
Labels: bug fix, hotfix⚡️
