Repository RedHatInsights/edge-api, pull requests merged in 2022-07, with the labels that each got.

#1236 add first boot option for rhc registration
  templates/templateKickstart.ks
Labels: waiting for review

#1253 Drop and make account Nullable for image_set
  pkg/routes/imagesets.go
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
Labels: waiting for review

#1245 Checking queries params
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/routes/devices.go
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/routes/query_params.go
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
Labels: waiting for review

#1269 fix validation for reboot when rebase or upgrad run
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
Labels: do not merge

#1259 THEEDGE-2231 Fix update transaction when device is disconnected
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix, test update

#1279 drop account from repo build service
  pkg/services/repobuilder.go
Labels: waiting for review

#1289 THEEDGE-2406 Fix device update with status disconnected
  pkg/models/updates.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix, test update

#1296 THEEDGE-2412 Fix device upgrading when does not exists on inventory
  cmd/spec/main.go
  cmd/spec/path.yaml
  pkg/routes/common/response.go
  pkg/routes/updates.go
  pkg/routes/updates_test.go
Labels: bug fix, test update

#1299 clowder images-build microservice config
  Dockerfile
  deploy/clowdapp.yaml
Labels: waiting for review

#1309 update path api spec file
  cmd/spec/path.yaml
Labels: documentation

#1308 THEEDGE-2414 imageID was missing as a query param for thirdpartyrepo
  pkg/routes/query_params.go
Labels: waiting for review
