Repository RedHatInsights/edge-api, pull requests merged in 2022-05, with the labels that each got.

#1016 Image: Add image installer reserved username validation.
  pkg/models/images.go
  pkg/models/images_test.go
  pkg/routes/images_test.go
Labels: bug fix

#1017 inventory-events: FIXES RHCClientID may be empty, deleted device may not exist.
  pkg/services/devices.go
Labels: bug fix

#1018 Remove ayosef from codeowners :/
  .github/CODEOWNERS
Labels: waiting for review

#1041 images: FIXES custom repos validation.
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug

#1030 Found small spell correction
  pkg/services/thirdpartyrepo.go
Labels: waiting for review

#1055 Update readme file with podman/docker instructions
  README.md
Labels: documentation

#1053 custom-repos: FIXES - route module.
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
Labels: waiting for review

#1072 upgrade gorm sqlite to 1.3.2
  go.mod
  go.sum
  pkg/services/ownershipvoucher_unit_test.go
Labels: dependencies

#1065 Theedge 2136 update all devices from group
  cmd/spec/main.go
  cmd/spec/path.yaml
  pkg/models/updates.go
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/routes/updates.go
  pkg/services/mock_services/commits.go
  pkg/services/mock_services/updates.go
  pkg/services/updates.go
Labels: invalid
