Repository RedHatInsights/edge-api, pull requests merged in 2022-04, with the labels that each got.

#898 THEEDGE-1998 create common to manage the identity
  pkg/clients/client.go
  pkg/dependencies/main.go
  pkg/routes/common/identity.go
Labels: enhancement

#886 devices: Update db devices when creating an image (update) or when upgrading a device.
  pkg/services/errors.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
  pkg/services/mock_services/updates.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: enhancement, ready

#906 THEEDGE-1948 endpoint validate images selection to update
  cmd/spec/main.go
  cmd/spec/path.yaml
  pkg/routes/updates.go
  pkg/routes/updates_test.go
  pkg/services/mock_services/updates.go
  pkg/services/updates.go
Labels: documentation, new feature

#918 Add a parameter to get only the latest update
  cmd/spec/path.yaml
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/mock_services/devices.go
Labels: waiting for review

#929 Remove slash on route update validate
  pkg/routes/updates.go
Labels: bug fix

#937 Change migrate/wipe to better handle errors and panics
  cmd/db/wipe.go
  cmd/migrate/main.go
Labels: waiting for review

#939 fix response from update validate on path.yaml
  cmd/spec/path.yaml
Labels: documentation

#953 THEEDGE-1928: Add devicegroups/devices many2many back reference
  pkg/models/devices.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/errors.go
Labels: ready

#944 Group validator
  cmd/spec/path.yaml
  pkg/routes/devicegroups.go
  pkg/services/devicegroups.go
  pkg/services/mock_services/devicegroups.go
Labels: waiting for review

#957 images: FIXES CheckIfIsLatestVersion.
  pkg/services/errors.go
  pkg/services/images.go
  pkg/services/images_test.go
Labels: waiting for review, bug fix, hotfix⚡️

#948 add validation to do update device with same commit
  pkg/routes/updates.go
Labels: waiting for review

#970 DevicesView: FIXES Devices view filters.
  pkg/routes/devices.go
  pkg/services/devices.go
Labels: bug fix

#943 consumers: lock shuttingDown variable access.
  pkg/services/consumers.go
Labels: waiting for review

#969 add value to identify when a device its being updated
  pkg/models/devices.go
  pkg/services/devices.go
Labels: waiting for review

#1002 fix image info on devicesview route
  pkg/services/devices.go
Labels: bug fix
