Repository RedHatInsights/edge-api, pull requests merged in 2022-10, with the labels that each got.

#1526 fix condition on delete devices on sync process
  pkg/services/devices.go
Labels: bug fix

#1533 Increased test coverage for models.Images package to 100%
  .github/workflows/lint.yml
  cmd/kafka/main.go
  cmd/spec/main.go
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/clients/inventory/client.go
  pkg/clients/playbookdispatcher/client.go
  pkg/models/images.go
  pkg/models/images_test.go
  pkg/routes/images_test.go
  pkg/routes/storage_test.go
  pkg/services/files_test.go
  pkg/services/updates_test.go
Labels: test update

#1530 Added producer interface to allow mocking. Turned producer, topic and…
  pkg/common/kafka/kafka_suite_test.go
  pkg/common/kafka/kafkaconfigmap.go
  pkg/common/kafka/mock_kafka/mock_kafkaconfigmap.go
  pkg/common/kafka/mock_kafka/mock_producer.go
  pkg/common/kafka/mock_kafka/mock_topics.go
  pkg/common/kafka/producer.go
  pkg/common/kafka/producer_test.go
  pkg/common/kafka/topics.go
  pkg/routes/images.go
  pkg/services/consumers.go
  pkg/services/images.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/main.go
Labels: test update

#1546 Added more tests to services/images.go
  pkg/common/kafka/kafkaconfigmap.go
  pkg/services/images.go
  pkg/services/images_test.go
Labels: test update

#1541 Temporarily suppress issues reported by "make pre-commit"
  pkg/routes/storage.go
  pkg/routes/storage_test.go
  pkg/services/image/event_image_iso_requested_test.go
  pkg/services/image/image_suite_test.go
  pkg/services/images_build/main.go
  pkg/services/images_test.go
  pkg/services/repobuilder.go
Labels: good first issue, waiting for review

#1553 Fixed db test intermittent segment fault
  pkg/db/main_test.go
Labels: bug fix, test update

#1532 Add memory size check method to validate log's object size
  pkg/services/files/utils.go
  pkg/services/files/utils_test.go
Labels: new feature

#1543 update: Setup update playbook to use edge cert api endpoints.
  config/config.go
  deploy/clowdapp.yaml
  pkg/services/images_build/main.go
  pkg/services/updates.go
  pkg/services/updates_test.go
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
Labels: new feature

#1559 update: FIX update change refs variable.
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix, hotfix⚡️

#1561 update: Fix playbook template.
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
Labels: bug fix, hotfix⚡️

#1562 Add Og to CODEOWNERS
  .github/CODEOWNERS
Labels: bug fix

#1560 Make Github actions lint match Makefile and check all issues
  .github/workflows/lint.yml
  pkg/common/kafka/kafka_suite_test.go
  pkg/common/kafka/producer_test.go
Labels: bug fix

#1542 Remove PR approvals if new commits added
  .github/mergify.yml
Labels: waiting for review, new feature

#1570 edge2261: remove extraneous event models
  pkg/models/events.go
Labels: waiting for review

#1564 Add check that no unresolved conversation threads in PR before merging
  .github/mergify.yml
Labels: good first issue, waiting for review, new feature

#1579 image update: FIXES #THEEDGE-2732 parent ref when upgrading to major version.
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug fix, hotfix⚡️

#1567 thirdpartyrepo: Add end-point checkName.
  cmd/spec/path.yaml
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
  pkg/services/mock_services/thirdpartyrepo.go
  pkg/services/thirdpartyrepo.go
  pkg/services/thirdpartyrepo_test.go
Labels: waiting for review, bug fix, new feature

#1573 edge2261: update local dev podman-compose examples
  podman/container-compose-api.yml
  podman/container-compose-db.yml
  podman/container-compose-kafka.yml
  podman/container-compose-services.yml
  podman/env/edgemgmt_config.json
Labels: waiting for review, new feature

#1572 edge1704: add events_test
  pkg/models/events_test.go
Labels: test update

#1586 storage: remove storage installer account dependency.
  pkg/routes/storage.go
Labels: bug fix

#1588 update: make update to use the simple content reader end-point.
  pkg/services/updates.go
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
Labels: bug fix, hotfix⚡️

#1587 Display all golangci-lint errors sorted with filename and line number
  .github/workflows/lint.yml
  Makefile
  pkg/clients/imagebuilder/client_test.go
  pkg/models/events_test.go
Labels: new feature

#1555 update: make update transaction device repository as private on storage.
  pkg/services/files/uploader.go
  pkg/services/files/uploader_test.go
  pkg/services/mock_services/uploader.go
  pkg/services/repobuilder.go
Labels: waiting for review, new feature, test update

#1593 Disable unleash on thirdpartyrepo
  pkg/routes/thirdpartyrepo.go
Labels: bug fix

#1590 images: fixes images commit ostreeRef when previous image fail.
  pkg/services/images.go
Labels: waiting for review, bug fix, hotfix⚡️

#1599 Created an edge listener for unleash to control what we log.
  main.go
  unleash/edge_listener.go
Labels: new feature

#1602 refactor packageDiff sturcture in case there is no changes when comapring packages
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: bug fix

#1604 Make mergify rule names unique and use shared key
  .github/mergify.yml
Labels: waiting for review, bug fix

#1606 fix validation against commit and images, add scenario to prevent rol…
  pkg/routes/updates.go
  pkg/routes/updates_test.go
  pkg/services/commits.go
  pkg/services/commits_test.go
  pkg/services/errors.go
  pkg/services/updates_test.go
Labels: question, new feature, test update

#1611 add field to group and fix sqlstatement
  pkg/services/commits.go
Labels: waiting for review, bug fix
