Repository RedHatInsights/edge-api, pull requests merged in 2022-12, with the labels that each got.

#1706 escape character on search
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: bug fix

#1710 fix assertion
  pkg/clients/imagebuilder/client_test.go
Labels: test update

#1709 devices: fixes event_device_sync_test and add more coverage.
  pkg/services/devices/event_device_sync.go
  pkg/services/devices/event_device_sync_test.go
Labels: bug fix

#1712 Added a Where condition on getting image set view data to not include…
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
Labels: bug fix

#1691 create event of inventory that sync with Devices
  pkg/services/devices.go
  pkg/services/devices/event_inventory_sync.go
  pkg/services/devices/event_inventory_sync_test.go
  pkg/services/mock_services/devices.go
Labels: new feature

#1708 images: FIXES GetUpdateInfo.
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/errors.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: waiting for review, bug fix, test update

#1713 Added live probe for server readiness.
  config/config.go
  deploy/clowdapp.yaml
  go.mod
  main.go
  pkg/routes/readiness.go
  pkg/routes/readiness_test.go
Labels: test update

#1724 Slightly improved unittest for models.Devices.
  pkg/models/devices_test.go
Labels: test update

#1721 update: implement UpdateRepoRequested event.
  pkg/common/kafka/topics.go
  pkg/dependencies/main.go
  pkg/models/events.go
  pkg/services/mock_services/updates.go
  pkg/services/update/event_update_repo_requested.go
  pkg/services/update/event_update_repo_requested_test.go
  pkg/services/update/update_suite_test.go
  pkg/services/updates.go
  pkg/services/updates_test.go
  unleash/features/feature.go
Labels: waiting for review, new feature

#1731 workaround for missing inst.stage2 (BZ 2152192)
  scripts/fleetkick.sh
Labels: bug fix

#1735 fix connection leak in readiness
  pkg/routes/readiness.go
Labels: bug fix

#1733 devices: add index to image_id and optimise the negative query.
  pkg/models/devices.go
  pkg/routes/devices.go
Labels: bug fix

#1734 fixed path for GetImageSetsDevicesByID in the spec-file
  cmd/spec/path.yaml
Labels: documentation

#1672 add negative unit test to _image_iso
  pkg/models/1669888589141297608-models.db-journal
  pkg/services/images_iso/main.go
  pkg/services/images_iso/main_test.go
Labels: test update

#1743 Add unit test for pkg/routes/common/account.go
  pkg/routes/common/account_test.go
Labels: test update

#1747 Add unit test for pkg/routes/common/identityheadrs.go
  pkg/routes/common/identityheaders_test.go
Labels: test update

#1748 remove unused endpoint
  pkg/routes/devices.go
Labels: bug fix

#1752 Clean up db module and remove journal.
  pkg/db/main_test.go
  pkg/models/1669888589141297608-models.db-journal
  pkg/models/main_test.go
Labels: test update

#1741 move it from DeviceGroup end point to imporve performance
  pkg/models/devicegroups.go
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
Labels: bug fix

#1755 Improvements to pkg/db/db.org
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/routes/main_test.go
Labels: test update

#1751 image-sets: fixes image-sets-view updated_at.
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
Labels: waiting for review, bug fix, test update

#1759 add unit test to imageupdate request event
  pkg/services/image/event_image_update_requested.go
  pkg/services/image/event_image_update_requested_test.go
Labels: test update

#1764 image-sets-view: fixes image-sets-view sort_by updated-at.
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/services/imagesets.go
Labels: bug fix, test update, hotfix⚡️

#1769 image-sets-view: fixes sort dates and images latest status.
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/services/imagesets.go
Labels: bug fix, hotfix⚡️

#1770 image-sets-view: fixes image-sets-view deleted-at IS NOT NULL.
  pkg/services/imagesets.go
Labels: bug fix

#1772 image-sets-view: fixes image-sets-view count sql.
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
Labels: bug fix

#1774 image-sets-view: fixes image-sets view org-id selection.
  pkg/services/imagesets.go
Labels: bug fix, hotfix⚡️

#1761 move external url controller to commit object
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/models/commits.go
  pkg/services/mock_services/downloader.go
  pkg/services/mock_services/repobuilder.go
  pkg/services/repobuilder.go
  pkg/services/repobuilder_test.go
Labels: bug fix

#1756 Refactoring Edge configuration module.
  config/config.go
  config/config_suite_test.go
  config/config_test.go
Labels: waiting for review

#1776 Changed hardcoded metrics port plus resolving many pre-existing golan…
  deploy/clowdapp.yaml
  main.go
  pkg/common/kafka/consumer.go
  pkg/common/kafka/consumer_test.go
  pkg/db/db_test.go
  pkg/models/commits_test.go
  pkg/models/devices_test.go
  pkg/models/installers_test.go
  pkg/models/thirdpartyrepo_test.go
  pkg/models/updates_test.go
  pkg/routes/common/account_test.go
  pkg/routes/common/identity_test.go
  pkg/routes/common/identityheaders_test.go
  pkg/routes/common/org_id_test.go
  pkg/routes/images_test.go
  pkg/routes/readiness.go
  pkg/routes/readiness_test.go
  pkg/services/devices/event_device_sync.go
  pkg/services/devices/event_device_sync_test.go
  pkg/services/devices/event_inventory_sync.go
  pkg/services/devices/event_inventory_sync_test.go
  pkg/services/errors_test.go
  pkg/services/image/event_image_requested_test.go
  pkg/services/image/event_image_update_requested_test.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/images_iso_suite_test.go
  pkg/services/images_iso/main_test.go
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
  pkg/services/update/event_update_repo_requested.go
  pkg/services/update/event_update_repo_requested_test.go
Labels: bug fix

#1780 Remove deprecated option and travis comments from mergify
  .github/mergify.yml
Labels: bug fix

#1775 fixed list-image-sets route count query
  pkg/routes/imagesets.go
Labels: waiting for review
