Repository RedHatInsights/edge-api, pull requests merged in 2022-09, with the labels that each got.

#1398 Added Guidlines for PR's in the Contributing.md file.
  .github/mergify.yml
  CONTRIBUTING.md
Labels: documentation

#1391 change the object of deviceImageInfo to deviceImageSetInfo,
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
Labels: bug fix, new feature

#1455 Added the produce and consumer frame work for building ISO's.
  pkg/common/kafka/topics.go
  pkg/models/events.go
  pkg/services/image/event_image_iso_requested.go
  pkg/services/images.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/main.go
  unleash/features/feature.go
Labels: new feature

#1458 Fix mergify rule for removing 'waiting for review' label
  .github/mergify.yml
Labels: bug fix

#1463 remove field dupplication
  pkg/clients/inventory/client.go
Labels: bug fix

#1470 Fix unresponsive status
  pkg/services/devices.go
Labels: bug fix

#1464 update dev config file reader to workaround upstream issue
  config/config.go
  podman/container-compose-api.yml
  podman/container-compose-dependencies.yml
  podman/container-compose-services.yml
  podman/container-compose-ui.yml
  podman/env/edgemgmt_config.json
Labels: bug fix

#1417 Fix device creation
  pkg/models/commits.go
  pkg/models/devicegroups.go
  pkg/models/devices.go
  pkg/models/updates.go
  pkg/routes/devicegroups_test.go
  pkg/routes/devices_test.go
  pkg/routes/updates.go
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/images_test.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix

#1475 fix update status
  pkg/services/updates.go
Labels: bug fix

#1476 add requestedName to actualName topic lookup to NewConsumers
  main.go
  pkg/common/kafka/topics.go
  pkg/services/consumers.go
  podman/env/edgemgmt_config.json
Labels: new feature

#1477 fix dispatch record
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix

#1478 fix omit
  pkg/services/updates.go
Labels: bug fix

#1479 fix reference for device on dispatch record
  pkg/services/updates.go
Labels: bug fix

#1456 Add new "golangci-lint" target to Makefile
  Makefile
Labels: new feature

#1382 add retrycreateimage on case when worker stop responding
  pkg/clients/imagebuilder/client.go
  pkg/services/images.go
  pkg/services/images_test.go
Labels: new feature

#1485 add external app topics and dependencies to clowder
  deploy/clowdapp.yaml
Labels: new feature

#1486 THEEDGE-2588 - fix UpdateAllDeviceFromGroup function
  pkg/routes/devicegroups.go
Labels: bug fix

#1487 add requestedname to log
  pkg/common/kafka/topics.go
Labels: bug fix

#1489 Theedge 2342 validate by image set
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/services/devices.go
  pkg/services/updates.go
Labels: bug fix

#1396 Validate user provided commitID for different ImageSet to update device
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/routes/updates.go
  pkg/routes/updates_test.go
  pkg/services/commits.go
  pkg/services/devices.go
  pkg/services/errors.go
  pkg/services/mock_services/commits.go
Labels: bug fix

#1462 Added consume function for ISO processing microservice.
  Dockerfile
  deploy/clowdapp.yaml
  pkg/models/events.go
  pkg/services/image/event_image_iso_requested.go
  pkg/services/images.go
Labels: waiting for review, new feature

#1502 Setting new limit for sync devices
  pkg/services/devices.go
Labels: bug fix

#1499 Added isos-build pod via clowdapp config.
  deploy/clowdapp.yaml
Labels: waiting for review, new feature

#1503 Make golangci-lint and golangci-lint-no-fdo targets, changed pre-comm…
  Makefile
  config/config.go
  main.go
  pkg/models/thirdpartyrepo.go
  pkg/models/updates.go
  pkg/routes/images.go
  pkg/services/imagesets.go
  pkg/services/repobuilder.go
Labels: waiting for review, new feature

#1507 Remove Travis check from mergify since lint is done in Github action
  .github/mergify.yml
Labels: bug fix

#1513 update: Fix dipatcher-record model.
  pkg/models/updates.go
Labels: bug fix

#1511 Fixed test coverage step name, Added Codecode and removed from Travis
  .github/workflows/lint.yml
  .travis.yml
Labels: waiting for review

#1410 THEEDGE-2489: implement update repo security.
  cmd/spec/path.yaml
  config/config.go
  deploy/clowdapp.yaml
  main.go
  pkg/models/updates.go
  pkg/routes/signature/signature.go
  pkg/routes/signature/signature_suite_test.go
  pkg/routes/signature/signature_test.go
  pkg/routes/storage.go
  pkg/routes/storage_test.go
  pkg/services/files/uploader.go
  pkg/services/files/uploader_test.go
  pkg/services/mock_services/uploader.go
  pkg/services/repobuilder.go
  pkg/services/updates.go
  pkg/services/updates_test.go
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
Labels: new feature, test update

#1515 Modified the context for each event to include the services. Initiali…
  pkg/services/image/event_image_iso_requested.go
  pkg/services/image/event_image_iso_requested_test.go
  pkg/services/image/event_image_requested.go
  pkg/services/image/event_image_update_requested.go
  pkg/services/image/image_suite_test.go
  pkg/services/images_build/main.go
  pkg/services/images_iso/main.go
Labels: test update
