Repository RedHatInsights/edge-api, pull requests merged in 2022-08, with the labels that each got.

#1325 request-filters: FIXES contain filters that should be in group.
  pkg/routes/common/filters.go
  pkg/routes/common/filters_test.go
Labels: waiting for review, bug fix

#1336 route-filters: Add unit-test for IntegerNumberFilterHandler.
  pkg/routes/common/filters_test.go
Labels: waiting for review

#1342 fix a bug - THEEDGE-2461
  pkg/routes/updates.go
Labels: waiting for review

#1356 Update path.yaml
  cmd/spec/path.yaml
Labels: documentation

#1358 Update path.yaml
  cmd/spec/path.yaml
Labels: documentation

#1360 THEEDGE-2377 Add update status reasons
  pkg/models/updates.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: new feature

#1357 move account from update
  pkg/services/updates.go
Labels: waiting for review

#1390 Add validation to image_id filter on devicesview
  pkg/routes/devices.go
  pkg/routes/devices_test.go
Labels: waiting for review, bug fix

#1384 Run in java container like marketplace does
  .gitignore
  sonarqube.sh
  sonarqube_exec.sh
Labels: waiting for review

#1383 Refactored config to remove duplication.
  config/config.go
  pkg/common/kafka/producer.go
Labels: waiting for review

#1403 THEEDGE-2377 Update transactions reasons missing cases
  pkg/clients/playbookdispatcher/mock_playbookdispatcher/playbookdispatcher.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: enhancement, waiting for review

#1393 Add query params validation for /updates endpoint
  pkg/routes/query_params.go
  pkg/routes/updates.go
  pkg/routes/updates_test.go
Labels: waiting for review, bug fix

#1401 Bash fix for docker
  .gitignore
  sonarqube.sh
  sonarqube_exec.sh
Labels: waiting for review

#1413 remove producer from INTERRUPTED resume loop
  cmd/kafka/main.go
Labels: waiting for review

#1414 remove image-build consumer from Edge API consumers
  main.go
  pkg/services/consumers.go
  pkg/services/consumers_test.go
Labels: waiting for review
