Repository RedHatInsights/edge-api, pull requests merged in 2023-09, with the labels that each got.

#2215 image-builder-client: Fixes repository gpgkey json representation.
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: bug fix, test update

#2218 add static delta state functions and flags
  pkg/models/staticdelta.go
  pkg/models/staticdelta_test.go
  unleash/features/feature.go
Labels: waiting for review, bug fix, new feature, test update

#2226 fix params at imageSet documentation
  pkg/routes/imagesets.go
Labels: documentation

#2209 migration-groups: create inventory groups client.
  pkg/clients/inventorygroups/client.go
  pkg/clients/inventorygroups/client_test.go
  pkg/models/devicegroups.go
Labels: new feature

#2230 repositories: Add origin and content_type to content-sources queries.
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
Labels: new feature

#2228 add debug to service repo builder call for static delta
  pkg/db/db.go
  pkg/services/updates.go
  unleash/features/feature.go
Labels: bug fix, new feature

#2232 fix commitService in Update service debugging
  pkg/services/updates.go
Labels: bug fix

#2235 add delta check and state read/write
  pkg/models/staticdelta.go
  pkg/services/main_test.go
  pkg/services/repobuilder.go
  pkg/services/updates.go
  unleash/features/feature.go
Labels: new feature

#2239 fix static delta ostree commits
  pkg/models/staticdelta.go
  pkg/services/updates.go
Labels: bug fix, new feature

#2238 add feature flag to block the api request
  pkg/routes/devicegroups.go
  unleash/features/feature.go
Labels: new feature

#2241 add preload old commits to update query
  pkg/services/updates.go
Labels: bug fix

#2249 devices-view: return inventory groups with devices.
  pkg/models/devices.go
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: new feature

#2252 devices-view: hotfix POST devicesview endpoint.
  pkg/routes/devices.go
Labels: bug fix, hotfix⚡️
