Repository RedHatInsights/edge-api, pull requests merged in 2023-10, with the labels that each got.

#2253 add wait for ready to static delta process
  pkg/models/staticdelta.go
  pkg/services/repobuilder.go
  pkg/services/updates.go
  unleash/features/feature.go
Labels: bug fix, new feature

#2245 groups-migration: edge-parity groups migration.
  Dockerfile
  cmd/migrategroups/main.go
  cmd/migrategroups/migrategroups/migrategroups.go
  cmd/migrategroups/migrategroups/migrategroups_suite_test.go
  cmd/migrategroups/migrategroups/migrategroups_test.go
  deploy/clowdapp.yaml
  pkg/clients/inventorygroups/client.go
  pkg/clients/inventorygroups/mock_inventorygroups/client.go
  unleash/features/feature.go
Labels: new feature

#2265 golang: upgrade to go version 1.19.
  .github/workflows/lint.yml
  .travis.yml
  Dockerfile
  Makefile
  README.md
  build_deploy.sh
  go.mod
  pkg/clients/imagebuilder/client_test.go
  podman/Containerfile-dev
  pr_check.sh
Labels: bug fix

#2270 go-toolset: update to latest container base version.
  Dockerfile
  build_deploy.sh
  podman/Containerfile-dev
  pr_check.sh
Labels: bug fix

#2263 add continue after static delta
  pkg/services/updates.go
Labels: waiting for review, bug fix

#2266 add group uuid as parameter for deviceview endpoint
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/routes/query_params.go
Labels: new feature

#2282 go-tools: update to latest ubi8/go-toolset image
  Dockerfile
  build_deploy.sh
  podman/Containerfile-dev
  pr_check.sh
Labels: bug fix
