Repository RedHatInsights/edge-api, pull requests merged in 2023-12, with the labels that each got.

#2326 add support to RHEL-93 and RHEL-89
  config/repo_config.go
Labels: waiting for review, new feature

#2340 devicesview: return empty list when no devices
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: new feature

#2351 inventory-client: remove staleness param from inventory query
  pkg/clients/inventory/client.go
  pkg/clients/inventory/client_suite_test.go
  pkg/clients/inventory/client_test.go
Labels: bug fix
