Repository RedHatInsights/edge-api, pull requests merged in 2023-07, with the labels that each got.

#2120 cleanup: Setup openshift CronJob to never restart on failure.
  cmd/cleanup/cleanupimages/cleanupimages.go
  deploy/clowdapp.yaml
Labels: bug fix

#2123 cleanup: fixes cleanup images script.
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanupimages/cleanupimages_test.go
  deploy/clowdapp.yaml
Labels: bug fix, test update, hotfix⚡️

#2124 cleanup: redo back cleanup images values.
  cmd/cleanup/cleanupimages/cleanupimages.go
  deploy/clowdapp.yaml
Labels: new feature

#2125 cleanup: implement a retry when deleting s3 bucket folders.
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanupimages/cleanupimages_test.go
  deploy/clowdapp.yaml
Labels: bug fix, new feature, test update

#2110 fix insights collect data after reboot
  templates/templateKickstart.ks
Labels: waiting for review, bug fix

#2130 add support on swaggo in go.mod file
  go.mod
  go.sum
Labels: waiting for review

#2134 cleanup: run all page cleanup-images in threads.
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanupimages/cleanupimages_test.go
  config/config.go
Labels: new feature, test update

#2113 create imageset_api
  pkg/models/images_api.go
  pkg/models/imagesets_api.go
  pkg/routes/images.go
  pkg/routes/imagesets.go
Labels: documentation, new feature

#2133 Description for imageset api
  pkg/models/imagesets_api.go
Labels: documentation, waiting for review

#2139 cleanup: implement CLEANUP_SUSPEND
  cmd/cleanup/cleanupimages/cleanupimages.go
  deploy/clowdapp.yaml
Labels: new feature

#2127 add support for /devices end point in Swagger
  pkg/models/devices_api.go
  pkg/routes/devices.go
  pkg/routes/imagesets.go
Labels: documentation, question

#2148 api-doc: API doc for thirdpartyrepo endpoints.
  pkg/models/thirdpartyrepo_api.go
  pkg/routes/thirdpartyrepo.go
Labels: documentation

#2154 api-doc: FIXES API doc for thirdpartyrepo endpoints.
  pkg/routes/thirdpartyrepo.go
Labels: bug fix, new feature

#2152 Implement the api doc for create device-groups
  .gitignore
  pkg/models/devicegroups_api.go
  pkg/routes/devicegroups.go
Labels: documentation

#2153 add static delta state struct and db schema migrate
  cmd/migrate/main.go
  pkg/models/staticdelta.go
  pkg/models/staticdelta_test.go
Labels: bug fix

#2151 add example and description to device api
  pkg/models/devices_api.go
Labels: documentation, waiting for review

#2160 add ostree summary command to static delta gen
  Makefile
  pkg/services/repobuilder.go
  pkg/services/repobuilder_test.go
Labels: waiting for review, bug fix

#2158 Configure mergify to squash commit instead of merge.
  .github/mergify.yml
Labels: waiting for review

#2161 add more example to decice_api
  pkg/models/devices_api.go
Labels: waiting for review

#2164 cleanup: move storage functions to storage module.
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanupimages/cleanupimages_test.go
  cmd/cleanup/storage/storage.go
  cmd/cleanup/storage/storage_suite_test.go
  cmd/cleanup/storage/storage_test.go
Labels: new feature, test update
