Repository RedHatInsights/edge-api, pull requests merged in 2023-04, with the labels that each got.

#1986 content-sources: add client CreateRepository.
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
  pkg/clients/repositories/mock_repositories/client.go
Labels: new feature

#1989 Theedge 3252 add content validation
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
  pkg/clients/repositories/mock_repositories/client.go
  pkg/routes/common/identity_test.go
  pkg/routes/readiness.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/imagesets.go
Labels: new feature

#1992 content-sources: Apply the same rules as for content-sources repos.
  pkg/models/thirdpartyrepo.go
  pkg/models/thirdpartyrepo_test.go
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
  pkg/services/errors.go
  pkg/services/errors_test.go
  pkg/services/images_test.go
  pkg/services/mock_services/thirdpartyrepo.go
  pkg/services/thirdpartyrepo.go
  pkg/services/thirdpartyrepo_test.go
Labels: waiting for review, new feature

#1994 fix ostree remote overwrite
  templates/template_playbook_dispatcher_ostree_rebase_payload.test.yml
  templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.test.yml
  templates/template_playbook_dispatcher_ostree_upgrade_payload.yml
Labels: waiting for review, bug fix, new feature

#2000 handle response code when playbook dispatcher not found(perf)
  pkg/clients/playbookdispatcher/client.go
Labels: bug fix

#2002 content-sources: Create a migration preparation script to comply with content-sources rules.
  Dockerfile
  cmd/migraterepos/main.go
  cmd/migraterepos/repairrepos/repairrepos.go
  cmd/migraterepos/repairrepos/repairrepos_suite_test.go
  cmd/migraterepos/repairrepos/repairrepos_test.go
  deploy/clowdapp.yaml
  pkg/models/thirdpartyrepo.go
  podman/Containerfile-dev
  podman/container-compose-reposmigrate.yml
  unleash/features/feature.go
Labels: new feature

#2011 content-sources: update migration preparation script to comply with content-sources rules.
  cmd/migraterepos/repairrepos/repairrepos.go
  cmd/migraterepos/repairrepos/repairrepos_test.go
Labels: new feature

#2012 content-sources: update migration repos script to configure unleash client
  cmd/migraterepos/main.go
Labels: bug fix, new feature, hotfix⚡️

#2014 content-sources: update migration repos script to configure unleash client.
  cmd/migraterepos/main.go
Labels: bug fix

#2020 content-sources: migrate custom repositories to content-sources.
  cmd/migraterepos/main.go
  cmd/migraterepos/migraterepos/migraterepos.go
  cmd/migraterepos/migraterepos/migraterepos_suite_test.go
  cmd/migraterepos/migraterepos/migraterepos_test.go
Labels: waiting for review, new feature
