Repository RedHatInsights/edge-api, pull requests merged in 2023-06, with the labels that each got.

#2074 image-sets: fixes undocumented delete methods with documented one.
  go.mod
  go.sum
  pkg/services/imagesets.go
Labels: waiting for review, bug fix

#2086 add repo file upload retry with configurable number of attempts
  config/config.go
  pkg/services/files/uploader.go
  pkg/services/files/uploader_test.go
Labels: bug fix

#2090 fix repo url reference
  pkg/services/repobuilder.go
Labels: bug fix

#2091 fix repo url reference with direct get commit
  pkg/services/commits.go
  pkg/services/repobuilder.go
Labels: bug fix

#2077 image-sets: run delete images in one transaction with image-set.
  pkg/services/imagesets.go
Labels: waiting for review, bug fix

#2093 images: FIXES orphan images raised when building images.
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/image/event_image_requested.go
  pkg/services/image/event_image_requested_test.go
  pkg/services/image/event_image_update_requested.go
  pkg/services/image/event_image_update_requested_test.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: bug fix

#2094 add step for permissive rhcd_t on start
  templates/templateKickstart.ks
Labels: waiting for review, new feature

#2105 api docs add new struct example and annotations
  pkg/models/images_api.go
  pkg/routes/devicegroups.go
  pkg/routes/devices.go
  pkg/routes/images.go
  pkg/routes/imagesets.go
  pkg/routes/storage.go
  pkg/routes/thirdpartyrepo.go
  pkg/routes/updates.go
Labels: waiting for review, new feature

#2109 images: Implement images storage cleanup.
  Dockerfile
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanupimages/cleanupimages_suite_test.go
  cmd/cleanup/cleanupimages/cleanupimages_test.go
  cmd/cleanup/main.go
  pkg/models/images.go
  pkg/routes/images.go
  pkg/services/files/s3.go
  pkg/services/files/s3_test.go
  pkg/services/mock_files/s3.go
  podman/Containerfile-dev
  unleash/features/feature.go
Labels: new feature

#2112 cleanup: add unleash.WaitForReady.
  cmd/cleanup/main.go
Labels: bug fix

#2114 cleanup: copy cleanup binary to container /usr/bin.
  Dockerfile
Labels: bug fix, hotfix⚡️

#2117 cleanup: unleash.WaitForReady() on successful initialization.
  cmd/cleanup/main.go
Labels: bug fix

#2118 cleanup: Setup openshift CronJob for cleanup instance.
  deploy/clowdapp.yaml
Labels: new feature
