Repository RedHatInsights/edge-api, pull requests merged in 2023-05, with the labels that each got.

#2022 add post migration flag to custom repositories
  unleash/features/feature.go
Labels: new feature

#2030 content-sources: custom repositories migration - add migrated to conflicting name.
  cmd/migraterepos/migraterepos/migraterepos.go
  cmd/migraterepos/migraterepos/migraterepos_test.go
Labels: new feature, test update

#2026 Post migrate delete custom repository
  cmd/migraterepos/main.go
  cmd/migraterepos/postmigraterepos/postmigraterepos.go
  cmd/migraterepos/postmigraterepos/postmigraterepos_suite_test.go
  cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
Labels: new feature

#2055 hotfix for bonfire bootstrap script
  pr_check.sh
Labels: bug fix

#2051 add support to 8.8 and 9.2
  config/repo_config.go
Labels: question, waiting for review, new feature

#2048 images: replace GetRepositoryByUUID with GetRepositoryByURL.
  pkg/services/images.go
  pkg/services/images_test.go
Labels: waiting for review, bug fix

#2062 devices_test: fixes limit when calling deviceService.GetDevicesView.
  pkg/services/devices_test.go
Labels: bug fix, test update, hotfix⚡️

#2068 add condition to deleted_at
  pkg/routes/images.go
  pkg/routes/imagesets.go
Labels: bug fix
