Repository RedHatInsights/edge-api, pull requests merged in 2023-03, with the labels that each got.

#1932 remove validation of env to set gpg verify; Define always as false;
  config/config.go
  templates/template_playbook_dispatcher_ostree_rebase_payload_prod.test.yml
Labels: bug fix

#1933 update code owners
  .github/CODEOWNERS
Labels: documentation

#1937 content-sources: add content-sources config and client
  config/config.go
  config/config_test.go
  deploy/clowdapp.yaml
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
  pkg/clients/repositories/mock_repositories/client.go
Labels: waiting for review, new feature

#1885 Test scan
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/clients/imagebuilder/mock_imagebuilder/client.go
  pkg/models/commits.go
  pkg/services/images_test.go
  unleash/features/feature.go
Labels: bug fix

#1944 Fix commits save
  pkg/clients/imagebuilder/client.go
Labels: bug fix

#1943 content-sources: add GetRepositoryByName and refactor ListRepositories.
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
Labels: new feature, test update

#1906 Tls https Client
  config/config.go
  config/config_test.go
  main.go
  pkg/clients/client.go
  pkg/clients/clients_test.go
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/clients/playbookdispatcher/client.go
Labels: new feature

#1946 Theedge 3077 extend model
  pkg/models/thirdpartyrepo.go
  pkg/models/thirdpartyrepo_test.go
Labels: waiting for review

#1951 content-sources: API return HMS repositories
  pkg/clients/repositories/mock_repositories/client.go
  pkg/dependencies/main.go
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: new feature, test update

#1959 Add tls to content source
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
Labels: waiting for review

#1958 content-sources: submit content-sources repositories to image builder.
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
Labels: new feature, test update

#1967 content-sources: Add 2 more functions to repositories client.
  pkg/clients/repositories/client.go
  pkg/clients/repositories/clients_test.go
  pkg/clients/repositories/mock_repositories/client.go
Labels: new feature

#1969 removing OneOf from /updates in path.yml
  cmd/spec/path.yaml
Labels: bug fix

#1972 content-sources: ignore non-existent content-sources repositories when updating images.
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug fix, new feature, test update

#1977 fix user ssh directory permissions and ownership
  templates/templateKickstart.ks
Labels: bug fix

#1980 content-sources: prohibit any changes to repos when feature flag is enabled
  pkg/errors/api.go
  pkg/routes/thirdpartyrepo.go
  pkg/routes/thirdpartyrepo_test.go
Labels: new feature
