Repository RedHatInsights/edge-api, pull requests merged in 2023-01, with the labels that each got.

#1760 remove min replicas to ibievents and isobuild
  deploy/clowdapp.yaml
Labels: waiting for review, bug fix

#1793 updates: FIXES ValidateUpdateSelection images.
  pkg/services/updates.go
Labels: bug fix, hotfix⚡️

#1804 image-sets: Fixes image-sets linter problems and remove any linter skipping.
  pkg/routes/imagesets.go
  pkg/routes/imagesets_test.go
  pkg/services/imagesets.go
  pkg/services/imagesets_test.go
  pkg/services/mock_services/imagesets.go
Labels: bug fix

#1797 Removing unnecessary and sensitive information from kafka logs
  pkg/common/kafka/producer.go
Labels: waiting for review, bug fix

#1806 image-sets: remove the deprecated ioutil.ReadAll.
  pkg/routes/imagesets_test.go
Labels: bug fix

#1808 Add clean target to Makefile
  Makefile
Labels: new feature

#1809 Add Codecov Token
  .github/workflows/lint.yml
Labels: bug fix

#1810 Change setup-python action major version from 3 to 4
  .github/workflows/lint.yml
Labels: bug fix

#1811 fix count condition
  pkg/services/updates.go
Labels: bug fix

#1801 New unit test to device model
  pkg/models/devices_test.go
Labels: test update

#1798 s3: increase aws s3 coverage files module .
  pkg/services/files.go
  pkg/services/files/downloader.go
  pkg/services/files/downloader_test.go
  pkg/services/files/s3.go
  pkg/services/files/s3_test.go
  pkg/services/files/uploader.go
  pkg/services/files/uploader_test.go
  pkg/services/files_test.go
  pkg/services/mock_files/s3.go
Labels: waiting for review

#1803 add unit test to kafkaconfigmap
  pkg/common/kafka/kafkaconfigmap_test.go
Labels: waiting for review, test update

#1815 updates: Fixes linters and checkers errors.
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix

#1677 change the main of image_build and write unit test for that
  pkg/services/images_build/images_build_suite_test.go
  pkg/services/images_build/main.go
  pkg/services/images_build/main_test.go
Labels: test update

#1817 Add github-actions update to dependabot
  .github/dependabot.yml
Labels: new feature

#1825 Add ImageSetID to image creation event for notification link.
  pkg/services/images.go
Labels: new feature

#1819 THEEDGE-2960 Return the number of updates available on ImageInfo
  pkg/models/images.go
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/mock_services/devices.go
Labels: new feature, test update

#1832 device: Fixes GetDeviceImageInfo when first images failed.
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: bug fix

#1820 Create a index to Name field on thirdpartyrepo model
  pkg/models/thirdpartyrepo.go
Labels: waiting for review, new feature

#1823 add small changes for kafkabroker field
  pkg/common/kafka/kafkaconfigmap_test.go
Labels: waiting for review, test update

#1839 Fix formatting for payload and context
  pkg/services/images.go
Labels: bug fix

#1833 clients: add coverage to clients module.
  pkg/clients/clients_test.go
Labels: waiting for review, test update

#1837 images-consumer: Fixes images consumer tests gomock ctrl.Finish()
  pkg/services/image/event_image_iso_requested.go
  pkg/services/image/event_image_iso_requested_test.go
  pkg/services/image/event_image_requested_test.go
  pkg/services/image/event_image_update_requested_test.go
Labels: waiting for review, bug fix, test update

#1827 repobuilder: Add more coverage to repobuilder service.
  pkg/services/mock_files/extrator.go
  pkg/services/mock_files/uploader.go
  pkg/services/mock_services/repobuilder.go
  pkg/services/repobuilder.go
  pkg/services/repobuilder_test.go
Labels: waiting for review, bug fix, test update

#1836 devices: Fixes devices tests gomock ctrl.Finish().
  pkg/services/devices_test.go
Labels: bug fix

#1838 routes-services: Fixes gomock ctrl.Finish()
  pkg/routes/devices_test.go
  pkg/routes/imagesets_test.go
  pkg/routes/updates_test.go
  pkg/services/images_test.go
  pkg/services/updates_test.go
Labels: bug fix, test update

#1848 clowder: disable DVO check for erroneous ibvents failure
  deploy/clowdapp.yaml
Labels: bug fix

#1849 THEEDGE-3019 Fixes missing data when a device update finishes
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: bug fix, test update

#1851 images: FIXES change image name when updating.
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/errors.go
  pkg/services/images.go
  pkg/services/images_test.go
Labels: bug fix, test update

#1824 dd unit test to event in common/kafka
  pkg/common/kafka/events_test.go
Labels: test update
