Repository RedHatInsights/edge-api, pull requests merged in 2023-08, with the labels that each got.

#2169 add static delta state db read and write
  pkg/models/main_test.go
  pkg/models/staticdelta.go
  pkg/models/staticdelta_test.go
  pkg/services/repobuilder.go
Labels: bug fix, new feature

#2135 Update docs storage api
  cmd/spec/path.yaml
  pkg/routes/storage.go
Labels: documentation

#2176 cleanup: increase memory and cpu limits.
  deploy/clowdapp.yaml
Labels: bug fix

#2174 cleanup: Cleanup content of soft deleted devices.
  cmd/cleanup/cleanupdevices/cleanupdevices.go
  cmd/cleanup/cleanupdevices/cleanupdevices_suite_test.go
  cmd/cleanup/cleanupdevices/cleanupdevices_test.go
  cmd/cleanup/main.go
  pkg/models/updates.go
  unleash/features/feature.go
Labels: new feature

#2181 add error description and ID to image api
  pkg/models/images_api.go
  pkg/routes/images.go
Labels: documentation, waiting for review

#2195 linter: avoid Implicit memory aliasing
  pkg/clients/repositories/clients_test.go
  pkg/common/kafka/kafkaconfigmap_test.go
  pkg/routes/imagesets.go
  pkg/routes/thirdpartyrepo.go
Labels: bug fix

#2192 cleanup: fixes cleanup devices.
  cmd/cleanup/cleanupdevices/cleanupdevices.go
  cmd/cleanup/cleanupdevices/cleanupdevices_test.go
Labels: bug fix

#2196 cleanup: fixes cleanup devices.
  cmd/cleanup/cleanupdevices/cleanupdevices.go
Labels: bug fix

#2186 docs:Adding documentation to images.go on api
  pkg/routes/images.go
Labels: documentation

#2198 cleanup: cleanup orphan commits.
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits.go
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits_suite_test.go
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits_test.go
  cmd/cleanup/main.go
  unleash/features/feature.go
Labels: new feature

#2183 cleanup: implement delete images.
  cmd/cleanup/deleteimages/deleteimages.go
  cmd/cleanup/deleteimages/deleteimages_suite_test.go
  cmd/cleanup/deleteimages/deleteimages_test.go
  cmd/cleanup/main.go
  unleash/features/feature.go
Labels: waiting for review, new feature

#2200 cleanup: increase memory usage.
  deploy/clowdapp.yaml
Labels: bug fix

#2201 devicesview: fixes sharable gorm.db.
  pkg/routes/devices.go
Labels: bug fix

#2203 cleanup: fixes constraint violations errors.
  cmd/cleanup/cleanupdevices/cleanupdevices.go
  cmd/cleanup/cleanupimages/cleanupimages.go
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits.go
  deploy/clowdapp.yaml
Labels: bug fix

#2207 THEEDGE-3404 Change openapi to swaggo
  .gitignore
  Dockerfile
  Makefile
Labels: documentation

#2210 migrate-repos: FIXES migrate repos by adding OrgAdmin to user.
  cmd/migraterepos/migraterepos/migraterepos.go
  cmd/migraterepos/migraterepos/migraterepos_test.go
Labels: bug fix
