Repository RedHatInsights/edge-api, pull requests merged in 2024-04, with the labels that each got.

#2479 add unattended and sudoers options to blueprint
  pkg/clients/imagebuilder/client.go
  unleash/features/feature.go
Labels: new feature

#2476 fix: do not log readiness checks
  pkg/routes/readiness.go
Labels: waiting for review

#2482 fix sudoers group name
  pkg/clients/imagebuilder/client.go
Labels: bug fix

#2493 Improve console and migration logging
  cmd/migrate/main.go
  logger/logger.go
  pkg/db/db.go
Labels: question

#2498 Update database paths to use /tmp directory
  cmd/cleanup/cleanupdevices/cleanupdevices_suite_test.go
  cmd/cleanup/cleanupimages/cleanupimages_suite_test.go
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits_suite_test.go
  cmd/cleanup/deleteimages/deleteimages_suite_test.go
  cmd/migrategroups/migrategroups/migrategroups_suite_test.go
  cmd/migraterepos/migraterepos/migraterepos_suite_test.go
  cmd/migraterepos/postmigraterepos/postmigraterepos_suite_test.go
  cmd/migraterepos/repairrepos/repairrepos_suite_test.go
  pkg/clients/imagebuilder/client_test.go
  pkg/db/db_test.go
  pkg/db/main_test.go
  pkg/models/main_test.go
  pkg/routes/common/filters_test.go
  pkg/routes/main_test.go
  pkg/services/main_test.go
  pkg/services/update/update_suite_test.go
Labels: waiting for review

#2499 Add simple job scheduler
  internal/middleware/prometheus.go
  main.go
  pkg/jobs/dummy.go
  pkg/jobs/job.go
  pkg/jobs/memory.go
  pkg/jobs/memory_test.go
  pkg/jobs/queue.go
  pkg/metrics/metrics.go
  pkg/metrics/registration.go
  pkg/services/images.go
  unleash/features/feature.go
Labels: waiting for review

#2505 update startup logging
  main.go
Labels: bug fix

#2506 update log at startup
  config/config.go
Labels: bug fix

#2472 THEEDGE-3923: remove rhc first boot from edge mgmt
  templates/templateKickstart.ks
Labels: waiting for review

#2510 THEEDGE-3926: add active deadline for cleanup job
  deploy/clowdapp.yaml
Labels: bug fix

#2511 EDA remove deprecated image event calls from routes
  pkg/routes/images.go
  pkg/services/images_test.go
  unleash/features/feature.go
Labels: waiting for review

#2504 Add feature flag check with context
  pkg/services/images.go
  unleash/features/feature.go
Labels: question

#2512 EDA remove services defs
  Dockerfile
  deploy/clowdapp.yaml
Labels: question
