Repository RedHatInsights/edge-api, pull requests merged in 2024-06, with the labels that each got.

#2586 Add initial floorplan (HMS-3941)
  deploy/clowdapp.yaml
Labels: new feature

#2583 clowdapp: Add object storage for Pulp (HMS-4235)
  deploy/clowdapp.yaml
Labels: waiting for review, new feature

#2563 refactor: job queue for more go routines
  pkg/common/kafka/mock_kafka/mock_kafkaconfigmap.go
  pkg/common/kafka/mock_kafka/mock_producer.go
  pkg/common/kafka/mock_kafka/mock_topics.go
  pkg/jobs/job.go
  pkg/jobs/memory.go
  pkg/jobs/memory_test.go
  pkg/jobs/queue.go
  pkg/routes/images.go
  pkg/routes/images_test.go
  pkg/services/devices.go
  pkg/services/images.go
  pkg/services/images_test.go
  pkg/services/mock_services/images.go
  pkg/services/updates.go
Labels: waiting for review

#2589 trim leading/trailing whitespace from key
  pkg/clients/imagebuilder/client.go
Labels: bug fix

#2587 remove fdo from Makefile
  Makefile
Labels: waiting for review

#2614 Revert "increase cpu"
  deploy/clowdapp.yaml
Labels: waiting for review
