Repository RedHatInsights/edge-api, pull requests merged in 2024-02, with the labels that each got.

#2396 add improvements on subscription with activation key
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: bug fix

#2411 linter: fixes linter revive
  cmd/migrategroups/migrategroups/migrategroups.go
  cmd/migrategroups/migrategroups/migrategroups_test.go
  cmd/migraterepos/migraterepos/migraterepos_test.go
  cmd/migraterepos/postmigraterepos/postmigraterepos_test.go
  cmd/migraterepos/repairrepos/repairrepos.go
  cmd/migraterepos/repairrepos/repairrepos_test.go
  pkg/clients/clients_test.go
  pkg/clients/inventorygroups/client.go
  pkg/clients/inventorygroups/client_test.go
  pkg/clients/rbac/client.go
  pkg/clients/rbac/client_test.go
  pkg/clients/repositories/clients_test.go
  pkg/routes/common/pagination_test.go
  pkg/services/repobuilder_test.go
  pkg/services/updates.go
  pkg/services/updates_test.go
Labels: waiting for review

#2415 go-toolset: always use gotoolset latest minor version
  Dockerfile
  build_deploy.sh
  podman/Containerfile-dev
  pr_check.sh
Labels: waiting for review

#2414 devices-view: fixes devices-view when missing devices UUIDs
  pkg/routes/devices.go
  pkg/routes/devices_test.go
Labels: bug fix, test update

#2421 device: fixes create image when account is missing.
  pkg/routes/images.go
  pkg/routes/images_test.go
Labels: bug fix

#2425 fix json field value
  pkg/services/devices.go
Labels: bug fix

#2434 fix Unresponsive status on update and duplicate Inventory
  templates/templateKickstart.ks
Labels: bug fix

#2436 refactor insights client override to run after osbuild service on start
  templates/templateKickstart.ks
Labels: bug fix
