Repository RedHatInsights/edge-api, pull requests merged in 2024-07, with the labels that each got.

#2654 parse only commitmeta extension
  pkg/routes/storage.go
Labels: bug fix

#2653 fixes(HMS-4440): ADR-046 resource limits
  deploy/clowdapp.yaml
Labels: waiting for review

#2629 remove fdo routes
  README.md
  cmd/db/wipe.go
  cmd/migrate/main.go
  cmd/spec/main.go
  cmd/spec/path.yaml
  config/config.go
  deploy/clowdapp.yaml
  main.go
  pkg/clients/fdo/client.go
  pkg/clients/fdo/client_test.go
  pkg/clients/fdo/fdo_suite_test.go
  pkg/dependencies/main.go
  pkg/models/main_test.go
  pkg/models/ownershipvoucher.go
  pkg/models/ownershipvoucher_test.go
  pkg/routes/ownershipvoucher.go
  pkg/routes/ownershipvoucher_active.go
  pkg/services/main_test.go
  pkg/services/ownershipvoucher.go
  pkg/services/ownershipvoucher_active.go
  pkg/services/ownershipvoucher_test.go
  pkg/services/ownershipvoucher_unit_test.go
Labels: do not merge, waiting for review
