Repository RedHatInsights/edge-api, pull requests merged in 2024-01, with the labels that each got.

#2363 image: skip inject kickstart to iso.
  pkg/services/images.go
  pkg/services/images_test.go
  unleash/features/feature.go
Labels: waiting for review, new feature

#2365 image-builder: pass installer user and ssh-key to image-builder
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: new feature

#2367 golang: upgrade to golang 1.20
  .github/workflows/lint.yml
  .travis.yml
  Dockerfile
  Makefile
  README.md
  build_deploy.sh
  go.mod
  podman/Containerfile-dev
  pr_check.sh
Labels: documentation, enhancement

#2371 device-groups: fixes device-group rename
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/services/devicegroups.go
  pkg/services/devicegroups_test.go
Labels: bug fix

#2360 Theedge 3710: Add activation key to image model and add it on image builder request
  config/config.go
  config/config_test.go
  deploy/clowdapp.yaml
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  pkg/models/images.go
Labels: new feature

#2378 device-update: implement deviceUpdateImagesFilters
  pkg/models/updates.go
  pkg/routes/devices.go
  pkg/routes/devices_test.go
  pkg/services/devices.go
  pkg/services/devices_test.go
  pkg/services/errors.go
  pkg/services/mock_services/devices.go
Labels: bug fix, new feature

#2386 device-update: fixes deviceUpdateImagesFilters
  pkg/services/devices.go
  pkg/services/devices_test.go
Labels: bug fix

#2387 Fixed Subscription image builder orgId type
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: bug fix, test update

#2389 image-builder: add feature flag to pass user to image-builder
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
  unleash/features/feature.go
Labels: bug fix

#2390 image-builder: fixes users type passed to image-builder as slice
  pkg/clients/imagebuilder/client.go
  pkg/clients/imagebuilder/client_test.go
Labels: bug fix

#2381 Theedge 3815 notavailable
  pkg/routes/devicegroups.go
  pkg/routes/devicegroups_test.go
  pkg/services/utility/groups.go
Labels: new feature
