Repository RedHatInsights/edge-api, pull requests merged in 2024-05, with the labels that each got.

#2531 add a toggle to log fields for dev and debug
  logger/logger.go
  unleash/features/feature.go
Labels: question, waiting for review, new feature

#2544 jobs: job testing endpoints
  main.go
  pkg/jobs/job.go
  pkg/jobs/memory.go
  pkg/jobs/queue.go
  pkg/services/jobs.go
  unleash/features/feature.go
Labels: question

#2547 jobs: improve logging
  go.sum
  logger/ctx_hook.go
  pkg/dependencies/main.go
  pkg/services/images.go
Labels: question

#2548 jobs: store raw identity
  pkg/jobs/job.go
  pkg/services/images.go
Labels: question

#2551 jobs: simplify job creation
  pkg/jobs/job.go
  pkg/jobs/memory.go
  pkg/jobs/queue.go
  pkg/services/images.go
  pkg/services/jobs.go
Labels: question

#2555 Remove sonarqube in favor of Snyk
  Makefile
  build_deploy.sh
  pr_check.sh
  sonarqube.sh
Labels: waiting for review

#2557 chore: add pprof for stage
  main.go
  pkg/jobs/memory.go
Labels: question

#2549 mergify: Drop questions rule
  .github/mergify.yml
Labels: waiting for review

#2553 services: dbx helper
  go.sum
  pkg/services/commits.go
  pkg/services/devicegroups.go
  pkg/services/devices.go
  pkg/services/images.go
  pkg/services/imagesets.go
  pkg/services/repobuilder.go
  pkg/services/thirdpartyrepo.go
  pkg/services/updates.go
Labels: question, waiting for review

#2575 add pulp feature flag config
  unleash/features/feature.go
Labels: new feature

#2579 add 94 to repo config for updates
  config/repo_config.go
  pkg/services/devices.go
Labels: new feature
