Repository RedHatInsights/edge-api, pull requests merged in 2024-08, with the labels that each got.

#2675 remove old fixme and update description
  cmd/migrate/manual/000_history.go
Labels: do not merge

#2690 Remove trigger disable cleanup statements
  cmd/cleanup/cleanuporphancommits/cleanuporphancommits.go
Labels: waiting for review

#2697 Updating IQE trigger template for edge backend
  deploy/stage-post-deployment-tests.yaml
Labels: bug fix
